### ISSUE TITLE
About @timestamp

### ISSUE THREAD

**Issue by j0nix** [PhaedrusTheGreek/nagioscheckbeat#7]
Background:

Hey there, we use this great beat for transport custom performance metrics, since its all so easy to write and consume Nagios checks. 

We use a architecture where we deliver data to a loadbalancer with a bunch of logstash servers behind it, these servers leverage both Beats, collectd, syslog, logs then output to redis servers for consumption & later stored in elasticsearch  

The Problem:

When we have some problem, network or something, and nagioscheckbeat can't transport its batch, these are queued... right?

What we see is that sometimes we get a hole in the collection and then we get several values of that metrics with the same @timestamp, hence it seems that we have those missing metrics delivered at that time...

So... i have'nt investigated further about the details here but perhaps you have more insight, is this @timestamp manipulated by logstash or is this something that nagioscheckbeat do? 

- If nagioscheckbeat, could it be possible to add another timestamp reference?

**Comment by PhaedrusTheGreek** [comment]
It's possible that what you are seeing is the same check result delivered multiple times due to the network problem.   Beats & Logstash provides "at least once" delivery guarantee - meaning; if due to a network problem the ack is not received from the upstream system, we prefer to deliver again and risk duplicates rather than risk lost events.

If that is the case, the beats library (libbeat) has some things coming soon that will help prevent duplicates.

I can't see how Timestamp fields would be inaccurate because when the event is created, the [timestamp is taken before the check is executed](https://github.com/PhaedrusTheGreek/nagioscheckbeat/blob/master/check/check.go#L84-L88).   

- Can you show me some samples of the duplicate timestamp logs?    
- Also, what version of the beat are you running?

**Comment by j0nix** [comment]
**Yes, sorry for bothering you, but thanx for taking time.** 

- I have identified and fixed that network problem, that really was related to input/output resources on logstash servers. Now I don't see any strange graphs.

**So again, thanx for enlightening me of how it all works!**   

FYI: nagioscheckbeat-0.6.0-1.x86_64

**Comment by j0nix** [comment]
closing this issue
